/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersUserImport } from './routes/users/$user'
import { Route as SignLayoutImport } from './routes/_sign/_layout'
import { Route as SignLayoutSignUpImport } from './routes/_sign/_layout/sign-up'
import { Route as SignLayoutSignInImport } from './routes/_sign/_layout/sign-in'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserRoute = UsersUserImport.update({
  path: '/users/$user',
  getParentRoute: () => rootRoute,
} as any)

const SignLayoutRoute = SignLayoutImport.update({
  id: '/_sign/_layout',
  getParentRoute: () => rootRoute,
} as any)

const SignLayoutSignUpRoute = SignLayoutSignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => SignLayoutRoute,
} as any)

const SignLayoutSignInRoute = SignLayoutSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => SignLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_sign/_layout': {
      preLoaderRoute: typeof SignLayoutImport
      parentRoute: typeof rootRoute
    }
    '/users/$user': {
      preLoaderRoute: typeof UsersUserImport
      parentRoute: typeof rootRoute
    }
    '/_sign/_layout/sign-in': {
      preLoaderRoute: typeof SignLayoutSignInImport
      parentRoute: typeof SignLayoutImport
    }
    '/_sign/_layout/sign-up': {
      preLoaderRoute: typeof SignLayoutSignUpImport
      parentRoute: typeof SignLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SignLayoutRoute.addChildren([SignLayoutSignInRoute, SignLayoutSignUpRoute]),
  UsersUserRoute,
])

/* prettier-ignore-end */
